---
- hosts: all
  become: yes

  tasks:

    - name: stop current running container
      command: docker stop simple-devops-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm simple-devops-container
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi learncloud77/simple-image:latest
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull learncloud77/simple-image:latest

    - name: creating docker container using simple-image
      command: docker run -d --name simple-devops-container -p 8080:8080 learncloud77/simple-image:latest
