---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t simple-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag simple-image learncloud77/simple-image

    - name: push image on to dockerhub
      command: docker push learncloud77/simple-image

    - name: remove docker images from ansible server
      command: docker rmi tomcat simple-image:latest learncloud77/simple-image
      ignore_errors: yes
